= Aimtrainer

== Запуск проекта

Чтобы запустить проект, выполните команду:

  ddev start

Зайти в контейнер:

  ddev ssh

== Установка проекта

Чтобы установить проект, серверная часть:

  cd symfony
  composer install

Чтобы установить проект, клиентская часть:

  cd frontend
  yarn install

== Работа с базой данных

База данных PostgreSQL хранится в Docker volume, название которого можно посмотреть командой:

  docker volume ls

Обычно volume имеет имя вида:

  ddev-aimtrainer_db_data

Подключение к базе данных:

  host: aimtrainer.ddev.site
  port: 5432
  user: aimtrainer
  password: aimtrainer
  database: aimtrainer

== Порты

По умолчанию база данных доступна на порту:

  5432

Если этот порт занят или недоступен, узнайте, какой порт используется, командой:

  ddev describe

В выводе ищите раздел с базой данных и там будет актуальный порт для подключения.


== Frontend

При запуске сервера, нужно будет проверить папку frontend/node_modules/.cache и проставить ей права
sudo chown -R "имя_пользователя":"имя_пользователя" frontend/node_modules/.cache
